micronaut:
  application:
    name: keyManagerGRPC

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/keymanager
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    dialect: MARIADB
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau.account.url: 'http://localhost:9091'
bcb.pix.url: 'http://localhost:8082'